<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><LangVersion>5</LangVersion><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup><ItemGroup><ProjectReference Include="../BuddyMinecraft.csproj"/><Compile Include="Program.cs"/><Compile Include="SvgCanvas.cs"/><Compile Include="../tests/Checks.cs"/></ItemGroup></Project>
